#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook "apache2", ">= 0.99.4"
cookbook "mysql", ">= 1.0.5"
cookbook "build-essential"
cookbook "iis", ">= 1.6.2"
cookbook "openssl"
cookbook "php"
cookbook "wordpress",
  :git => 'https://github.com/derbandn/wordpress'
